const MENU_ITEMS = [
  {
    id: "waffle-base",
    category: "waffles",
    type: "food",
    name_ar: "وافل (الأساس)",
    name_en: "Waffle (Base)",
    desc_ar: "وافل طازج مع اختيار نكهة: وايت شوكليت أو شوكولاتة أو لوتس.",
    desc_en: "Fresh waffle base with flavor options: White Chocolate, Chocolate, or Lotus.",
    price: 50,
    image: "https://i.ibb.co/ymP0pFGs/f2d18ba695fad95cd48de4692422cb14.jpg",
    options: [
      { name_ar: "وايت شوكليت", name_en: "White Chocolate" },
      { name_ar: "شوكولاتة", name_en: "Chocolate" },
      { name_ar: "لوتس", name_en: "Lotus" }
    ],
    addOns: ["berry-spread", "strawberry-spread", "extra-milk-100ml"]
  },
  {
    id: "tea-regular",
    category: "hot",
    type: "drink",
    name_ar: "شاي عادي",
    name_en: "Tea (Regular)",
    desc_ar: "كوب شاي كلاسيكي بطعم متوازن.",
    desc_en: "Classic tea cup with a balanced flavor.",
    price: 15,
    image: "https://i.ibb.co/cXYFZjxd/08e0fc775e2ea3147fe78e25b47f2fc6.jpg"
  },
  {
    id: "green-tea",
    category: "hot",
    type: "drink",
    name_ar: "شاي أخضر",
    name_en: "Green Tea",
    desc_ar: "شاي أخضر خفيف ومنعش.",
    desc_en: "Light and refreshing green tea.",
    price: 15,
    image: "https://i.ibb.co/XZHN4nn3/5e0a169ef2ef17696893a2135d2d6b67.jpg"
  },
  {
    id: "fruit-tea",
    category: "hot",
    type: "drink",
    name_ar: "شاي فواكه",
    name_en: "Fruit Tea",
    desc_ar: "شاي فواكه بنكهة عطرية خفيفة.",
    desc_en: "Fruit tea with a light aromatic taste.",
    price: 15,
    image: "https://i.ibb.co/20z17MQ4/Chat-GPT-Image-9-2026-06-11-18.png"
  },
  {
    id: "french-tea",
    category: "hot",
    type: "drink",
    name_ar: "شاي فرنسي",
    name_en: "French Tea",
    desc_ar: "شاي فرنسي بطابع غني.",
    desc_en: "French tea with a rich profile.",
    price: 35,
    image: "https://i.ibb.co/239ZSpXn/6a8e6a043b4ba15f6b775c35e8fddaf9.jpg"
  },
  {
    id: "turkish-coffee",
    category: "hot",
    type: "drink",
    name_ar: "قهوة تركي",
    name_en: "Turkish Coffee",
    desc_ar: "قهوة تركي تقليدية قوية.",
    desc_en: "Traditional strong Turkish coffee.",
    price: 25,
    image: "https://i.ibb.co/Sb6YyTQ/b4f674e4c050f29a616f744ed433a8bf.jpg"
  },
  {
    id: "french-coffee",
    category: "hot",
    type: "drink",
    name_ar: "قهوة فرنسي",
    name_en: "French Coffee",
    desc_ar: "قهوة فرنسي بنكهة كريمية.",
    desc_en: "French coffee with a creamy profile.",
    price: 40,
    image: "https://i.ibb.co/VWP07fMv/81726082c6d0780cb89ef2d45a02684d.jpg"
  },
  {
    id: " black nescafe",
    category: "hot",
    type: "drink",
    name_ar: "نسكافيه بلاك",
    name_en: "Nescafe black",
    desc_ar: "نسكافيه سريع التحضير بطعم غني.",
    desc_en: "Rich instant Nescafe.",
    price: 20,
    image: "https://i.ibb.co/WpjdCNhs/Chat-GPT-Image-9-2026-06-20-15.png"
  },
  {
    id: "cocoa",
    category: "hot",
    type: "drink",
    name_ar: "كاكاو",
    name_en: "Cocoa",
    desc_ar: "مشروب كاكاو دافئ بطعم شوكولاتة.",
    desc_en: "Warm cocoa drink with chocolate taste.",
    price: 20,
    image: "https://i.ibb.co/fYqDV2XV/Chat-GPT-Image-9-2026-06-18-05.png"
  },
  {
    id: "hot-chocolate",
    category: "hot",
    type: "drink",
    name_ar: "هوت شوكليت",
    name_en: "Hot Chocolate",
    desc_ar: "هوت شوكليت غني وكريمي.",
    desc_en: "Creamy and rich hot chocolate.",
    price: 40,
    image: "https://i.ibb.co/Cf70fKT/Chat-GPT-Image-9-2026-06-13-20.png"
  },
  {
    id: "boiled-lemon",
    category: "hot",
    type: "drink",
    name_ar: "ليمون مغلي",
    name_en: "Boiled Lemon",
    desc_ar: "ليمون مغلي دافئ بطعم منعش.",
    desc_en: "Warm boiled lemon with a refreshing profile.",
    price: 15,
    image: "https://i.ibb.co/JwNhwCBx/Chat-GPT-Image-9-2026-06-10-14.png"
  },
  {
    id: "herbs",
    category: "hot",
    type: "drink",
    name_ar: "أعشاب",
    name_en: "Herbs",
    desc_ar: "كاركادي او ينسون او نعناع.",
    desc_en: "Karkade, anise, or mint .",
    price: 15,
    image: "https://i.ibb.co/zV173D1L/Chat-GPT-Image-9-2026-04-53-53.png"
  },
   {
    id: "cola-generic",
    category: "soft",
    type: "drink",
    name_ar: "كولا (عام)",
    name_en: "Cola (generic)",
    desc_ar: "مشروب غازي بارد.",
    desc_en: "Cold carbonated soft drink.",
    price: 25,
    image: "https://i.ibb.co/q3jXw3yc/COLA.png"
  },
  {
    id: "FURY",
    category: "soft",
    type: "drink",
    name_ar: "فيوري",
    name_en: "FURY",
    desc_ar: "فيوري بارد.",
    desc_en: "Chilled fury.",
    price: 30,
    image: "https://i.ibb.co/LzCJ7JwT/Screenshot-2026-02-08-163903.png"
  },
  {
    id: "red-bull",
    category: "energy",
    type: "drink",
    name_ar: "ريد بول",
    name_en: "Red Bull",
    desc_ar: "مشروب طاقة ريد بول.",
    desc_en: "Red Bull energy drink.",
    price: 70,
    image: "https://i.ibb.co/G4yDZNTN/Screenshot-2026-02-08-160548.png"
  },
  {
    id: "monster",
    category: "energy",
    type: "drink",
    name_ar: "مونستر",
    name_en: "Monster",
    desc_ar: "مشروب طاقة مونستر.",
    desc_en: "Monster energy drink.",
    price: 65,
    image: "https://i.ibb.co/hJ3FF4RD/Screenshot-2026-02-08-164750.png"
  },
  {
    id: "small-water",
    category: "water",
    type: "drink",
    name_ar: "مياه صغيرة",
    name_en: "Small Water",
    desc_ar: "زجاجة مياه صغيرة.",
    desc_en: "Small bottle of water.",
    price: 10,
    image: "https://i.ibb.co/XZ9NxRQq/7573bc72b72fe29124a5b0a0ec78f530.jpg"
  },
  {
    id: "large-water",
    category: "water",
    type: "drink",
    name_ar: "مياه كبيرة",
    name_en: "Large Water",
    desc_ar: "زجاجة مياه كبيرة.",
    desc_en: "Large bottle of water.",
    price: 20,
    image: "https://i.ibb.co/H5L09yb/ec66a6b92b5fc596c342727c035d1e21.jpg"
  },
  {
    id: "fresh-mango",
    category: "fresh",
    type: "drink",
    name_ar: "مانجو",
    name_en: "Mango",
    desc_ar: "عصير مانجو فريش.",
    desc_en: "Fresh mango juice.",
    price: 50,
    image: "https://i.ibb.co/kgkp69Z4/5b2e6e6c421542cfe71bc074e48cbdcf.jpg"
  },
  {
    id: "fresh-guava",
    category: "fresh",
    type: "drink",
    name_ar: "جوافة",
    name_en: "Guava",
    desc_ar: "عصير جوافة فريش.",
    desc_en: "Fresh guava juice.",
    price: 50,
    image: "https://i.ibb.co/Mk98gTxP/Chat-GPT-Image-9-2026-05-03-24.png"
  },
  {
    id: "fresh-strawberry",
    category: "fresh",
    type: "drink",
    name_ar: "فراولة",
    name_en: "Strawberry",
    desc_ar: "عصير فراولة فريش.",
    desc_en: "Fresh strawberry juice.",
    price: 50,
    image: "https://i.ibb.co/JjPCrsJt/40c723b8966afe0e96579653d76e63a5.jpg"
  },
  {
    id: "fresh-banana-milk",
    category: "fresh",
    type: "drink",
    name_ar: "موز بالحليب",
    name_en: "Banana Milk",
    desc_ar: "عصير موز بالحليب.",
    desc_en: "Fresh banana milk drink.",
    price: 50,
    image: "https://i.ibb.co/k2pgyCXz/Chat-GPT-Image-9-2026-05-11-00.png"
  },
  {
    id: "fresh-watermelon",
    category: "fresh",
    type: "drink",
    name_ar: "بطيخ",
    name_en: "Watermelon",
    desc_ar: "عصير بطيخ فريش.",
    desc_en: "Fresh watermelon juice.",
    price: 50,
    image: "https://i.ibb.co/n8zhkmbf/Chat-GPT-Image-9-2026-05-13-32.png"
  },
  {
    id: "fresh-lemon",
    category: "fresh",
    type: "drink",
    name_ar: "ليمون",
    name_en: "Lemon",
    desc_ar: "عصير ليمون فريش.",
    desc_en: "Fresh lemon juice.",
    price: 40,
    image: "https://i.ibb.co/cWF70wk/Chat-GPT-Image-9-2026-05-17-05.png"
  },
  {
    id: "fresh-lemon-mint",
    category: "fresh",
    type: "drink",
    name_ar: "ليمون نعناع",
    name_en: "Lemon Mint",
    desc_ar: "عصير ليمون بالنعناع.",
    desc_en: "Fresh lemon mint juice.",
    price: 45,
    image: "https://i.ibb.co/xKvcKDSn/Chat-GPT-Image-9-2026-05-16-04.png"
  },
  {
    id: "fresh-french-lemon",
    category: "fresh",
    type: "drink",
    name_ar: "ليمون فرنسي",
    name_en: "French Lemon",
    desc_ar: "عصير ليمون فرنسي مميز.",
    desc_en: "Special French lemon juice.",
    price: 50,
    image: "https://i.ibb.co/qYd2bHTp/Chat-GPT-Image-9-2026-05-56-55.png"
  },
  {
    id: "oreo-drink",
    category: "fresh",
    type: "drink",
    name_ar: "أوريو (مشروب)",
    name_en: "Oreo (drink)",
    desc_ar: "مشروب أوريو بارد وكريمي.",
    desc_en: "Cold and creamy Oreo drink.",
    price: 55,
    image: "https://i.ibb.co/cK4vtTbR/2ce9ffdbf8299bedea03f523ac301ecd.jpg"
  },
  {
    id: "berry-spread",
    category: "addons",
    type: "addon",
    name_ar: "صوص بيري",
    name_en: "Berry Spread",
    desc_ar: "إضافة للوافل.",
    desc_en: "Waffle add-on spread.",
    price: 15,
    image: "https://i.ibb.co/Y7dwFs8z/Chat-GPT-Image-9-2026-05-04-58.png"
  },
  {
    id: "strawberry-spread",
    category: "addons",
    type: "addon",
    name_ar: "صوص فراولة",
    name_en: "Strawberry Spread",
    desc_ar: "إضافة للوافل.",
    desc_en: "Waffle add-on spread.",
    price: 15,
    image: "https://i.ibb.co/Ld7nnbqB/Chat-GPT-Image-9-2026-05-05-53.png"
  },
  {
    id: "extra-milk-100ml",
    category: "addons",
    type: "addon",
    name_ar: "حليب إضافي 100 مل",
    name_en: "Extra Milk 100ml",
    desc_ar: "إضافة اختيارية للمشروبات الساخنة أو الوافل.",
    desc_en: "Optional add-on for hot drinks and waffles.",
    price: 20,
    image: "https://i.ibb.co/3yXYM3j6/4a45150d89610c93eb9b8335932296aa.jpg"
  }
];
